# Nombre de la aplicación
spring.application.name=relaciones

# Ruta hacia nuestras vistas JSP
spring.mvc.view.prefix=/WEB-INF/
spring.mvc.view.suffix=.jsp

# Conexión a base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/cancionesArtistas?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=YorelMySQLerum1738$
spring.jpa.hibernate.ddl-auto=update

# Para métodos PUT y DELETE a través de formularios
spring.mvc.hiddenmethod.filter.enabled=true